name: RegionDisplayName
version: '${project.version}'
main: net.jadedmc.regiondisplayname.RegionDisplayName
api-version: 1.13
depend:
  - WorldGuard
  - PlaceholderAPI

commands:
  regiondisplayname:
    description: RegionDisplayName main plugin command.
    aliases: [rdn]
    usage: /<command>
    permission: regiondisplayname.admin
